# -*- coding: utf-8 -*-
"""Aula6 Metodos de interpolacion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OXAk1wRQmnXnymmTXhmMoPVEZCRD8HmA
"""

import pandas as pd

data = [0.5, None, None, 0.52, 0.54, None, None, 0.59, 0.6, None, 0.7]
s = pd.Series(data)
s

s.fillna(0) #no sustituye porque no se puso el parametro inplace = True, solo muestra

s

s.fillna(method = 'ffill')  #comienza del inicio y reeemplaza los valores nulos por los valores validos anteriores mas cercanos al nulo...no sustituye porque no se puso el parametro inplace = True, solo muestra

s

s.fillna(method = 'bfill')  #comienza del final y reeemplaza los valores nulos por los valores validos anteriores mas cercanos al nulo...no sustituye porque no se puso el parametro inplace = True, solo muestra

s.fillna(s.mean()) #es el metodo mas usado para cambiar nulos, y reemplaza los valores nulos por la media aritmetica de la Series.. no sustituye porque no esta con inplace

s

s.fillna(method = 'ffill', limit = 1)  #se agrega el limite para no reemplace mas de un valor seguido porque no es correcto sustituir tantos puntos en secuencia dentro de una Series y para evitar tener un error estadistico en un grafico

s

s1 = s.fillna(method = 'ffill', limit = 1) 
s1

s2 = s1.fillna(method = 'bfill', limit = 1) 
s2

#s2 es la combinacion de un fillna con ffill y un fillna con bfill y se supone mas correcto que usar uno de los dos metodos solos