# -*- coding: utf-8 -*-
"""Aula9 Mas sobre graficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15UTrqyHtDsfL6mD7OHFHcvtSHVVt7r1v
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
plt.rc('figure', figsize= (15,10))

datos = pd.read_csv('alquiler_residencial_final_sin_outliers.csv', sep=';')
datos.head(10)

area = plt.figure()

g1 = area.add_subplot(2,2,1)     #configurando posiciones de los graficos
g2 = area.add_subplot(2,2,2)
g3 = area.add_subplot(2,2,3)
g4 = area.add_subplot(2,2,4)

#Crear graficos
g1.scatter(datos.Valor, datos.Area)  #grafico de dispersion de valor por area
g1.set_title('Valor x Area')

g2.hist(datos.Valor)              #histograma
g2.set_title('Histograma')

datos_g3 = datos.Valor.sample(100)       # sample toma una muestra aleatoria, en este caso de 100 registros
datos_g3.index = range(datos_g3.shape[0])  # corrigiendo los indices, genera nuevos indices del 0 al 99 en este caso
g3.plot(datos_g3)
g3.set_title('Muestra (Valor')

grupo = datos.groupby('Tipo')['Valor']   #crea una agrupacion de tipo y valor para crear un grafico de barras con la media de cada tipo de inmueble para alquilar
label = grupo.mean().index
valores = grupo.mean().values
g4.bar(label,valores)
g4.set_title('Valor Medio por Tipo')

area

area.savefig('grafico.png', dpi = 300, bbox_inches = 'tight')