# -*- coding: utf-8 -*-
"""Aula7 Creando nuevas variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mwjAyrjanpOsEur-iMEirOCwLylwJ-O8

#Reporte de Analisis VI

##Creando nuevas variables
"""

import pandas as pd

datos = pd.read_csv('alquiler_residencial.csv', sep=';')

datos.head(10)

datos['Valor Bruto'] = (datos['Valor']) + (datos['Mantenimiento']) + (datos['Impuesto']) #creando nueva variable Valor Bruto
datos.head(10)

datos['Valor m2'] = (datos['Valor']) / (datos['Area']) #creando nueva variable Valor por metro cuadrado
datos.head(10)

datos['Valor m2'] = datos['Valor m2'].round(2)  #redondea los decimales y deja solo 2
datos.head(10)

datos['Valor Bruto m2'] = ((datos['Valor Bruto']) / (datos['Area'])).round(2) #creando nueva variable Valor Bruto por m2 y redondeando
datos.head(10)

casa = ['Casa', 'Casa en condominio', 'Casa de villa']

datos['Tipo agrupado'] = datos['Tipo'].apply(lambda x: 'Casa' if x in casa else 'Departamento') #crea una nueva columna agrupando las casas segun la lista de arriba usando una funcion lambda
datos

datos.head(10)

"""##Excluyendo variables"""

datos.head(10)

datos_aux = pd.DataFrame(datos[['Tipo agrupado', 'Valor m2', 'Valor Bruto', 'Valor Bruto m2']]) #creando nuevo DataFrame para eliminar variables
datos_aux.head(10)

del datos_aux['Valor Bruto'] #eliminando Valor Bruto con del
datos_aux.head(10)

datos_aux.pop('Valor Bruto m2') #eliminando Valor Bruto m2 con pop, la diferencia con del es que pop muestra lo que borra al ejecutar mientras que del no muestra nada

datos_aux.head(10)

datos.head(10)

datos.drop(['Valor Bruto', 'Valor Bruto m2'], axis= 1, inplace = True) #eliminando con drop del DataFrame datos, pongo axis= 1 para indicar que es una columna, si no pongo nada busca una fila por defecto
datos.head(10)

datos.to_csv('alquiler_residencial.csv', sep=';', index= False)

