# -*- coding: utf-8 -*-
"""Aula4 Organizando DataFrames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KrLy9IN2l_pVf0cgm8nj-AG6Cy0ASClO
"""

import pandas as pd

data = [[1,2,3],[4,5,6],[7,8,9]]
data

list('321')

df = pd.DataFrame(data, list('321'), list('ZYX'))
df

df.sort_index(inplace = True) #ordenando los indices
df

df.sort_index(inplace = True, axis = 1)  #ordenando las columnas con axis
df

df.sort_values(by = 'X' ,inplace = True)  #ordenando el contenido del DataFrame por los valores de la columna X en forma ascendente
df

df.sort_values(by = '3', axis = 1 ,inplace = True)  #ordenando el contenido del DataFrame por los valores de la fila 3 en forma ascendente y ordenacion columnar(?)
df

