# -*- coding: utf-8 -*-
"""Aula5 ejercicios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oxKXAEkC2nlJeGJm8XCFwTrSwewwmbib
"""

import pandas as pd
alumnos = pd.DataFrame({
'Nombre': ['Ary', 'Katia', 'Denis', 'Beto', 'Bruna', 'Dara', 'Carlos', 'Alice'], 
'Sexo': ['M', 'F', 'M', 'M', 'F', 'F', 'M', 'F'], 
'Edad': [15, 27, 56, 32, 42, 21, 19, 35], 
'Notas': [7.5, 2.5, 5.0, 10, 8.2, 7, 6, 5.6], 
'Aprobado': [True, False, False, True, True, True, False, False]},
columns = ['Nombre', 'Edad', 'Sexo', 'Notas', 'Aprobado'])

alumnos

seleccion = alumnos['Aprobado'] == True  #Cree un DataFrame sólo con los estudiantes aprobados.
aprobados = alumnos[seleccion]
aprobados

seleccion = (alumnos.Aprobado == True) & (alumnos.Sexo == 'F')  #Cree un DataFrame sólo con las estudiantes aprobadas.
aprobadas = alumnos[seleccion]
aprobadas

seleccion = (alumnos.Edad > 10) & (alumnos.Edad < 20) | (alumnos.Edad >= 40)  #Cree sólo una visualización de los alumnos con edades entre 10 a 20 años o con edad mayor/igual a 40 años.
alumnos[seleccion]

seleccion = alumnos['Aprobado'] == False   #Cree un DataFrame sólo con los estudiantes reprobados y mantenga en este DataFrame sólo las columnas Nombre, Sexo y Edad, en este orden.
reprobados = alumnos[['Nombre', 'Sexo', 'Edad']][seleccion]
reprobados

seleccion = alumnos['Aprobado'] == False  #Cree un DataFrame sólo con los estudiantes reprobados y mantenga en este DataFrame sólo las columnas Nombre, Sexo y Edad, en este orden.
reprobados = alumnos.loc[seleccion, ['Nombre', 'Sexo', 'Edad']]
reprobados

alumnos.sort_values(by = ['Edad'], inplace = True)  #Crea una visualización con los tres alumnos más jóvenes.
alumnos.iloc[:3]

