# -*- coding: utf-8 -*-
"""Aula8 Creando rangos de valor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iup-VFnQqS3k_BIPccDrbOonyyJyELuV
"""

import pandas as pd

datos = pd.read_csv('alquiler.csv', sep=';')

datos.head(10)

#vamos a agrupar segun cantidad de cuartos
# 1 y 2
# 3 y 4
# 5 y 6
# 7 o mas cuartos
clases = [0 , 2, 4, 6, 100]

cuartos = pd.cut(datos.Cuartos, clases)
cuartos

pd.value_counts(cuartos)

label = ['1 y 2 cuartos', '3 y 4 cuartos', '5 y 6 cuartos', '7 o mas cuartos']

cuartos = pd.cut(datos.Cuartos, clases, labels = label)
cuartos

pd.value_counts(cuartos)

cuartos = pd.cut(datos.Cuartos, clases, labels = label, include_lowest = True)

pd.value_counts(cuartos)

