# -*- coding: utf-8 -*-
"""Aula3 Creando estructuras de datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NiKGXT2iY_covDddRgZYeDsZOZD7H_up
"""

import pandas as pd

"""# Series"""

data = [1,2,3,4,5]

s = pd.Series(data)
s

index = ['Linea' + str(i) for i in range(5)]
index

s = pd.Series(data = data, index = index)
s

data = {'Linea' + str(i) :i+1 for i in range(5)} #otra forma de hace lo mismo que en las dos lineas de codigo de arriba
data

s = pd.Series(data)
s

s1 = s +2
s1

s2 = s + s1 #se pueden realizar operaciones matemeticas entre series siempre y cuando tengan el mismo indice
s2

"""# DataFrames

##practica ejercicio aula
"""

datos = {'A': {'X': 1, 'Y': 3}, 'B': {'X': 2, 'Y': 4}}
df = pd.DataFrame(datos)
df

datos = [('A', 'B'), ('C', 'D')]
df = pd.DataFrame(datos, columns = ['L1', 'L2'],  index = ['C1', 'C2'])
df

df1 = pd.DataFrame({'A': {'X': 1}, 'B': {'X': 2}})
df2 = pd.DataFrame({'C': {'X': 3}, 'D': {'X': 4}})
pd.concat([df1, df2])

datos = [[1, 2, 3], [4, 5, 6]]
index = 'X,Y'.split(',')
columns = list('CBA')[::-1]
df = pd.DataFrame(datos, index, columns)
df

"""##video dataframes"""

data = [[1,2,3],[4,5,6],[7,8,9]] #lista de listas
data

df1 = pd.DataFrame(data = data)
df1

index = ['Linea' +str(i) for i in range(3)]
index

df1 = pd.DataFrame(data = data, index = index)
df1

columns = ['Columna' +str(i) for i in range(3)]
columns

df1 = pd.DataFrame(data = data, index = index, columns = columns)
df1

data = {'Columna0':{'Linea0':1, 'Linea1':4, 'Linea2':7},'Columna1':{'Linea0':2, 'Linea1':5, 'Linea2':8},'Columna2':{'Linea0':3, 'Linea1':6, 'Linea2':9}} #diccionario
data

df2 = pd.DataFrame(data)
df2

data2 = [(1,2,3),(4,5,6),(7,8,9)]  #lista de tuplas
data2

df3 = pd.DataFrame(data, index = index, columns = columns)
df3

df1[df1>0] = 'A'
df1

df2[df2>0] = 'B'
df2

df3[df3>0] = 'C'
df3

df4 = pd.concat([ df1, df2, df3])
df4

df5 = pd.concat([ df1, df2, df3], axis = 1)
df5

