# -*- coding: utf-8 -*-
"""Aula9 Identificando y Excluyendo Outliers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UzNAbt1jlwY5i98np1FzfUMuIb2v3Q47

#Reporte de Analisis VIII

##Identificando y Excluyendo Outliers
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
plt.rc('figure', figsize= (14,6))

datos = pd.read_csv('alquiler_residencial.csv', sep=';')
datos.head(10)

datos.boxplot(['Valor'])

datos[datos['Valor'] >= 500000]

valor = datos['Valor']

#datos para el boxplot real 
Q1 = valor.quantile(.25)
Q3 = valor.quantile(.75)
IIQ = Q3 - Q1
limite_inferior = Q1 - 1.5 * IIQ
limite_superior = Q3 + 1.5 * IIQ

seleccion = (valor >= limite_inferior) & (valor <= limite_superior)

datos_new = datos[seleccion]

datos_new.boxplot(['Valor'])

#nos indica que la mayoria de los valores de alquiler estan entre 1700 aprox y 4200 siendo la media 2300 aprox. tambien nos muestra que hay ciertos valores que van desde 
# 8300 aprox a 11000 que podrian ser otra categoria de alquiler (ej alquileres de alto nivel )

datos.hist(['Valor'])

datos_new.hist(['Valor'])

#este histograma de los datos ya arreglados nos muestra que la mayoria de los alquileres estan en el rango de valor de 2000

"""##ejercicio aula"""

valor_m2 = datos['Valor m2']

#datos para el boxplot real 
Q1 = valor_m2.quantile(.25)

Q3 = valor_m2.quantile(.75)

IIQ = Q3 - Q1

limite_inferior = Q1 - 1.5 * IIQ

limite_superior = Q3 + 1.5 * IIQ

Q1

Q3

IIQ

limite_inferior

limite_superior

"""
##Identificando y excluyendo Outliers (continuacion)"""

datos.boxplot(['Valor'], by = ['Tipo'])

grupo_tipo = datos.groupby('Tipo')['Valor']  #agrupa la columna Valor segun el Tipo de inmueble

type(grupo_tipo)

grupo_tipo.groups

#datos para el boxplot real 
Q1 = grupo_tipo.quantile(.25)
Q3 = grupo_tipo.quantile(.75)
IIQ = Q3 - Q1
limite_inferior = Q1 - 1.5 * IIQ
limite_superior = Q3 + 1.5 * IIQ

limite_inferior

limite_superior

datos_new = pd.DataFrame()
for tipo in grupo_tipo.groups.keys():
  eh_tipo = datos['Tipo'] == tipo
  eh_dentro_limite = (datos['Valor'] >= limite_inferior[tipo]) & (datos['Valor'] <= limite_superior[tipo])
  seleccion = eh_tipo & eh_dentro_limite
  datos_seleccion = datos[seleccion]
  datos_new = pd.concat([datos_new, datos_seleccion])

datos_new.boxplot(['Valor'], by = ['Tipo'])

datos_new.to_csv('alquiler_residencial_final_sin_outliers.csv', sep=';', index = False)

