# -*- coding: utf-8 -*-
"""Aula3 tipo_de_inmueble.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VSx3NniVLTpChOIgeP36oWkEWJ-TqSQE
"""

import pandas as pd

datos = pd.read_csv('alquiler.csv', sep = ';')

datos.head(10)

datos['Tipo']

datos.Tipo

tipo_de_inmueble = datos.Tipo

type(tipo_de_inmueble)

tipo_de_inmueble.drop_duplicates()

tipo_de_inmueble

tipo_de_inmueble.drop_duplicates(inplace = True)

tipo_de_inmueble

"""# Organizando la visualizacion"""

tipo_de_inmueble.index

tipo_de_inmueble = pd.DataFrame(tipo_de_inmueble)

type(tipo_de_inmueble)

tipo_de_inmueble.shape[0]

range(tipo_de_inmueble.shape[0])

for i in range(tipo_de_inmueble.shape[0]):
  print(i)

tipo_de_inmueble.index = range(tipo_de_inmueble.shape[0])

tipo_de_inmueble.index

tipo_de_inmueble

tipo_de_inmueble.columns.name = 'Id'

tipo_de_inmueble

