# -*- coding: utf-8 -*-
"""Aula7 Contadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8wyZPSBWvTqP9ri-Ep-i5X9nXkYq2qs
"""

import pandas as pd

list('asqadsdfasdfvadsfvdszfvadv')

s = pd.Series(list('asqadsdfasdfvadsfvdszfvadv'))
s

s.unique() #muestra los elementos unicos de la serie

s.value_counts() #muestra la frecuencia que se repite cada elemento de la series

datos = pd.read_csv('alquiler.csv', sep=';')
datos.head(10)

datos.Tipo.unique()

datos.Tipo.value_counts()

