# -*- coding: utf-8 -*-
"""Aula5 Formas de seleccion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YTGVRWIGN4nez666JzG4ChZKvs5NhbuU
"""

import pandas as pd

'l1 l2 l3 l4'.split()

data = [(1,2,3,4),
        (5,6,7,8),
        (9,10,11,12),
        (13,14,15,16)]
df = pd.DataFrame(data, 'l1 l2 l3 l4'.split(), 'c1 c2 c3 c4'.split())
df

df['c1']

type(df['c1'])

df[['c3', 'c1']]

type(df[['c3', 'c1']])

df

df[1:3]

df

df[1:][['c3','c1']]

df

df.loc['l3']

df.loc[['l3','l2']]

df

df.loc['l1','c2']  #loc utiliza el nombre de la fila y/o columna

df.iloc[0, 1]  #iloc utiliza el indice de la fila y/o columna

df.loc[['l3','l1'],['c4', 'c1']]

df.iloc[[2,0],[3, 0]]

