# -*- coding: utf-8 -*-
"""Importando base de datos de diferentes tipos de archivo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BWJP8hSMoSJjJaPxqsAsB13EANJCCIOl
"""

import pandas as pd

json = open('datos/alquiler.json')
print(json.read())

df_json = pd.read_json('datos/alquiler.json')
df_json

txt = open('datos/alquiler.txt')
print(txt.read())

df_txt = pd.read_table('datos/alquiler.txt')
df_txt

df_xlsx = pd.read_excel('datos/alquiler.xlsx')
df_xlsx

df_html1 = pd.read_html('datos/datos_html_1.html')
df_html1[0]

