# -*- coding: utf-8 -*-
"""Python Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YxB-auSXwEL5X_Os6fOnRVySbz6EdPDb
"""

!python -V

"""#Reporte de Analisis I

##Importando la base de datos
"""

import pandas as pd
pd.set_option('display.max_rows',15)
pd.set_option('display.max_columns',15)

dataset = pd.read_csv('alquiler.csv', sep=';')

dataset

dataset.describe()

type(dataset)

dataset.info()

dataset.head(10)

"""##Informaciones generales sobre la base de datos"""

dataset.dtypes

tipo_de_datos = pd.DataFrame(dataset.dtypes, columns = ['Tipos de datos'])

tipo_de_datos.columns.name = 'Variables'

tipo_de_datos

dataset.shape

dataset.shape[0]

dataset.shape[1]

print('La base de datos presenta {} registros (inmuebles) y {} variables'.format(dataset.shape[0], dataset.shape[1]))

